project:
  type: website

website:
  title: " Joshua Arvind's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Projects
      - icon: github
        href: https://github.com/jarvind20
      - icon: linkedin
        href: https://www.linkedin.com/in/joshua-arvind0101/
      - icon: envelope
        text: "Email"
        href: mailto:joshua.arvind@gmail.com
      - icon: telephone
        text: "Phone"
        href: "tel:703-889-7810"
      - text: "Last Updated: 1-14-26"
      
        
        

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    
    
    
